---
# inside feature branches it's handy to change the 'version' field to match the branch name
# as reported by the Github Action workflow 'publish.yaml', so that you can force HomeAssistant
# to use the docker image of that feature branch instead of the docker image of 'main', by pointing
# HomeAssistant to that feature branch
version: 3.3.0
slug: voip-client
name: voip-client
description: A VOIP client based on Baresip
url: https://github.com/f18m/ha-addon-voip-client-server/tree/main
# advanced true means that the HA user can see this addon only if it's flagged as 'advanced' in the
# Home Assistant UI
advanced: false
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
host_network: false
image: ghcr.io/f18m/{arch}-addon-voip-client
# init false because this addon uses s6-overlay
init: false

# no UI for now:
# enable the ingress feature for this addon, see https://developers.home-assistant.io/docs/add-ons/presentation#ingress
#ingress: true
#ingress_port: 8100
#panel_icon: mdi:ip-network-outline
#panel_title: DHCP

# For compatibility with dss_voip addon, we'll take input from stdin
stdin: true

options:
  # see DOCS.md for documentation on each setting
  voip_provider:
    # the name of the VOIP provider, e.g. "sipgate"
    name: "sipgate"
    # the SIP account to use for outgoing calls, in the format
    #  <sip:user@domain;uri-params>
    account: "<sip:user@example.com;transport=tcp>"
    # the username to use for authentication with the VOIP provider
    #username: "your-username"
    # the password to use for authentication with the VOIP provider
    password: "your-password"
schema:
  voip_provider:
    name: str
    account: str
    password: str

# categorize this addon as a "system" addon
startup: system
